[development]
DEBUG=*

NODE_RPI_GPIO=GPIO21

NODE_INFLUX_USER=<user>
NODE_INFLUX_PASS=<password>
NODE_INFLUX_HOST=<host>
NODE_INFLUX_PORT=8086
NODE_INFLUX_DATABASE=<database>
NODE_INFLUX_PROTOCOL=http
NODE_INFLUX_SERIES_NAME=phonebooth
NODE_INFLUX_DRYRUN=true

NODE_APP_PORT=3000
NODE_APP_TYPE=sensor
NODE_APP_BUILDING=<building_name>

NODE_HONEYBADGER_KEY=<key>

NODE_AGENT_ENDPOINT=<menagerie_endpoint>
NODE_DEVICE_TYPE_NAME=RPi PIR Sensor
NODE_AGENT_TOKEN=<token>

NODE_AMQP_ENDPOINT=<amqp_endpoint>
NODE_AMQP_EXCHANGE=<amqp_exchange>


[production]
DEBUG=*

NODE_RPI_GPIO=GPIO21

NODE_INFLUX_USER=<user>
NODE_INFLUX_PASS=<password>
NODE_INFLUX_HOST=<host>
NODE_INFLUX_PORT=8086
NODE_INFLUX_DATABASE=<database>
NODE_INFLUX_PROTOCOL=http
NODE_INFLUX_SERIES_NAME=phonebooth
NODE_INFLUX_DRYRUN=true

NODE_APP_PORT=3000
NODE_APP_TYPE=sensor
NODE_APP_BUILDING=<building_name>

NODE_HONEYBADGER_KEY=<key>

NODE_AGENT_ENDPOINT=<menagerie_endpoint>
NODE_DEVICE_TYPE_NAME=RPi PIR Sensor
NODE_AGENT_TOKEN=<token>

NODE_AMQP_ENDPOINT=<amqp_endpoint>
NODE_AMQP_EXCHANGE=<amqp_exchange>
