#!/bin/bash

DEBUG={{DEBUG}}

{% if NODE_RPI_REPL %}
NODE_RPI_REPL={{NODE_RPI_REPL}}
{% endif %}
NODE_RPI_ID={{NODE_RPI_ID}}
NODE_RPI_GPIO={{NODE_RPI_GPIO}}
NODE_RPI_ARCH=arm

NODE_INFLUX_USER={{NODE_INFLUX_USER}}
NODE_INFLUX_PASS={{NODE_INFLUX_PASS}}
NODE_INFLUX_HOST={{NODE_INFLUX_HOST}}
NODE_INFLUX_PORT={{NODE_INFLUX_PORT}}
NODE_INFLUX_DATABASE={{NODE_INFLUX_DATABASE}}
NODE_INFLUX_PROTOCOL={{NODE_INFLUX_PROTOCOL}}
NODE_INFLUX_SERIES_NAME={{NODE_INFLUX_SERIES_NAME}}
NODE_INFLUX_DRYRUN={{NODE_INFLUX_DRYRUN || false}}

NODE_APP_PORT={{NODE_APP_PORT}}
NODE_APP_TYPE={{NODE_APP_TYPE}}
NODE_APP_FLOOR={{NODE_APP_FLOOR}}
NODE_APP_BUILDING={{NODE_APP_BUILDING}}

NODE_DEVICE_UUID={{NODE_DEVICE_UUID}}

NODE_HONEYBADGER_KEY={{NODE_HONEYBADGER_KEY}}

NODE_AGENT_TOKEN={{NODE_AGENT_TOKEN}}
NODE_AGENT_ENDPOINT={{NODE_AGENT_ENDPOINT}}
NODE_DEVICE_TYPE_NAME={{NODE_DEVICE_TYPE_NAME}}

{% if NODE_AGENT_METADATA %}
NODE_AGENT_METADATA={{NODE_AGENT_METADATA|safe}}
{%endif%}

NODE_AMQP_EXCHANGE={{NODE_AMQP_EXCHANGE}}
NODE_AMQP_ENDPOINT={{NODE_AMQP_ENDPOINT}}
