#!/bin/bash

#################################
# This script should be fired from
# the src directory. Paths are
# relative to that :)
#################################

# ./bin/daemon

#Let's run docker
#Include our env var file, we define all our environment variables there
docker run --env-file .env -v /dev/mem:/dev/mem -v /lib/modules:/lib/modules --cap-add=ALL --privileged -p 3000:3000 --restart=always -d goliatone/rpi-pir-sensor
