#!/bin/bash

#################################
# This script should be fired from
# the src directory. Paths are
# relative to that :)
#################################


#Include our env var file, we define all our environment variables there
docker build -t goliatone/rpi-pir-sensor .

