#!/bin/bash

#################################
# This script should be fired from
# the src directory. Paths are
# relative to that :)
#################################


#Include our env var file, we define all our environment variables there
. .env


# ./bin/daemon

#Let's run docker
docker run -v /dev/mem:/dev/mem -v /lib/modules:/lib/modules --cap-add=ALL --privileged -p 3000:3000 -d rpi-pir-sensor
