#!/bin/bash

cd ~/CODE/rpi-pir-sensor

echo "Updating local repository..."
git pull

echo "docker build goliatone/rpi-pir-sensor..."
docker build --rm -t goliatone/rpi-pir-sensor .

echo "docker push goliatone/rpi-pir-sensor..."
docker push goliatone/rpi-pir-sensor
