#!/bin/bash

echo "Pull goliatone/rpi-pir-sensor..."
docker pull goliatone/rpi-pir-sensor:latest

echo "docker stop wee-sensor..."
! docker stop $(docker ps)

echo "docker remove old images..."
! docker rm -v $(docker ps -a -q -f status=exited)

echo "docker remove dangling images..."
! docker rmi $(docker images -f "dangling=true" -q)

echo "docker run..."
docker run --name=wee-sensor --env-file .env -v /dev/mem:/dev/mem -v /lib/modules:/lib/modules --cap-add=ALL --privileged -p 3000:3000 --restart=always -d goliatone/rpi-pir-sensor:latest
