#!/bin/bash

echo "Pull goliatone/rpi-pir-sensor..."
docker pull goliatone/rpi-pir-sensor:latest

echo "docker stop containers..."


CONTAINERS=$(docker ps -q)

if [ -n "$CONTAINERS" ]; then
    ! docker stop $CONTAINERS
else
    echo "No containers to remove."
fi

echo "docker remove old images..."
! docker rm $(docker ps -a -q)

echo "docker remove dangling images..."
! docker rmi $(docker images -q -f dangling=true)

echo "\ndocker run..."
docker run --name=wee-sensor --env-file .env -v /dev/mem:/dev/mem -v /lib/modules:/lib/modules --cap-add=ALL --privileged -p 3000:3000 --restart=always -d goliatone/rpi-pir-sensor:latest
